refactors/collisions
aperezcastagnino/tecina pull request #11
Opened 2024-11-10 13:37 UTC by aperezcastagnino

2024-11-10 15:10 UTC, paulacianelli commented on frontend/src/assets/asset-keys.ts
> +        NAME: "AWARD",
si el otro se llama AWARDEYE le pondria AWARDSTART a este

2024-11-10 15:12 UTC, paulacianelli commented on frontend/src/scenes/game-over.ts
> +    // Agregar un mensaje para reiniciar o salir
Esta bueno que dejemos los commetns del codigo en ingles asi queda consistente

2024-11-10 15:12 UTC, paulacianelli commented on frontend/src/scenes/game-over.ts
> +      this.scene.start("MainScene"); // Cambia 'MainScene' por el nombre de tu escena principal
same aca

2024-11-10 15:27 UTC, paulacianelli commented on frontend/src/scenes/preloader.ts
> +
En la linea 62 deberia ser 
:  AssetKeys.LEVELS.TILESET.TILESETIMAGE,

2024-11-11 22:48 UTC, aperezcastagnino commented on frontend/src/scenes/game-over.ts
> +    // Agregar un mensaje para reiniciar o salir
yep. aunque igual el nivel de game-over asi como esta no va existir, este me lo traje de la branch de nico

2024-11-11 22:50 UTC, aperezcastagnino commented on frontend/src/assets/asset-keys.ts
> +        NAME: "AWARD",
esto lo deje para que funcione el nivel, no se si va morir o no cuando agregue el tema de los npcs y los awards

2024-11-11 22:50 UTC, aperezcastagnino commented on frontend/src/scenes/preloader.ts
> +
same arriba

2024-11-11 22:51 UTC, aperezcastagnino commented
> Estas mergeando a development, no vamos a mergear a main ?

como hablamo el otro dia en wpp. una vez que quede todo el tema de las colisiones sip pero todavia no esta terminado.
en main estan los npcs con las colisiones viejas y este pr tiene las colisiones nuevas. para no trancarte fue que splitee el refactor y para no pisar a main fue la creacion de main

2024-11-12 01:00 UTC, nicolas968 requested changes

2024-11-12 01:00 UTC, nicolas968 commented on frontend/src/scenes/level1.ts
> +    collisionLayer.setCollisionByProperty({ colisionable: true });
esto es necesario?

2024-11-12 01:00 UTC, nicolas968 commented on frontend/src/scenes/level1.ts
>      this.cameras.main.fadeIn(1000, 0, 0, 0);
Esto es algo generico no? habria que moverlo pa otro lado

2024-11-12 01:00 UTC, nicolas968 commented on frontend/src/scenes/level1.ts
>        "tileset_sunnysideworld",
esto no tendria que estar aca

2024-11-12 01:28 UTC, aperezcastagnino commented on frontend/src/scenes/level1.ts
>      this.cameras.main.fadeIn(1000, 0, 0, 0);
la camara?

2024-11-12 01:29 UTC, aperezcastagnino commented on frontend/src/scenes/level1.ts
>        "tileset_sunnysideworld",
ya lo charlamo cabeza

2024-11-12 01:29 UTC, aperezcastagnino commented on frontend/src/scenes/level1.ts
> +    collisionLayer.setCollisionByProperty({ colisionable: true });
no probe sacarla, esto vino parte de tus cambios. luego pruebo que onda

2024-11-12 01:53 UTC, aperezcastagnino commented on frontend/src/scenes/level1.ts
> +    collisionLayer.setCollisionByProperty({ colisionable: true });
no hace falta, asi que la pelo

2024-11-12 02:24 UTC, nicolas968 approved these changes

2024-11-12 12:45 UTC, merged